### ISSUE TITLE
Communications about translations working group and translator recruitment

### ISSUE THREAD

**Issue by melissawm** [Quansight-Labs/czi-scientific-python-mgmt#107]
## Summary
Develop a communication and engagement strategy to recruit translators and facilitate translations work for the selected projects.

## Acceptance Criteria
Establish a group of at least 1 translator per language (at least 3 languages) for all projects. 

## Tasks to complete
- [ ] Record video on using crowdin for translations, to share with new translators.
- [ ] Write blog post for blog.scientific-python.org on translations work to share on social media
- [ ] Select social media channels to share blog post and recruitment messages
    - [ ] Target each project's twitter/mastodon/linkedin/mailing list/forum 
    - [ ] Share on Scientific Python communication channels
- [ ] Engage and monitor `#translations` channel on the Scientific Python discord
- [ ] Add issues and relevant discussions to https://github.com/orgs/Scientific-Python-Translations/projects/1 for record-keeping and information

**Comment by goanpeca** [comment]
We now have established the discord channel for translator communications.

Closing! :)
