### ISSUE TITLE
Develop translation workflows - narrative content

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-scientific-python-mgmt#13]
## 📝 Summary

Develop and provide well-documented translation workflows for narrative content in documentation sites using the PyData Sphinx theme.

## 🚀 Tasks / Deliverables

- [x] Develop translation workflow
- [x] Add documentation for the workflows (maintainers and contributors)
- [ ] Add translation workflows to target sites

## 📅 Estimated completion

[24 months milestone](https://github.com/Quansight-Labs/czi-scientific-python-mgmt/milestone/2)

## 📋 Additional information

-

**Comment by trallard** [comment]
AFAIK this is completed @melissawm @goanpeca
