### ISSUE TITLE
ENH - Theme improvements to the PyData Sphinx theme (colour and focus)

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-scientific-python-mgmt#20]
## 📝  Summary

Related to #8 

- [A colour contrast check was done by @scmmmh](https://github.com/pydata/pydata-sphinx-theme/issues/1052) and determined it was best to work on a cohesive colour system for the theme, which will lead to:
	- Adaptable theming - dark and light 
	- Improved maintainability
	- Better out-of-the-box colour contrast conformance (Meet [WCAG SC 1.4.3 - contrast AA](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum))
- While working on the colour system, additional design and UX interaction had been done to help with other WCAG criteria

## Acceptance Criteria

- [WCAG SC 1.4.3 - text contrast AA](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum)
	- 4.5:1 ratio for text and background (text < 18pt or bold text < 14pt)
	- 3:1 ratio for text and background (text >= 18pt or bold text =< 14pt)
- Focus visible criteria - buttons, links, and navigation components meet at least WCAG 2.1 (designs account for changes in [WCAG 2.2](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance.html)
	-  [WCAG 2.1 SC 2.4.7](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible)
- [WCAG SC 1.4.11 - non-text contrast AA](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast) need a minimum 3:1 contrast ratio with adjacent colours
	- link underline
	- focus styles
	- buttons and badges
	- icons
	- dropdowns
- [WCAG SC 1.4.1 - use of colour](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color)
	- Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element

```[tasklist]
### Tasks
- [x] Generate design system proposals (See tracking issue in the PyData Sphinx theme repository)
- [x] Decide on a path forward (select proposal)
- [ ] https://github.com/Quansight-Labs/czi-scientific-python-mgmt/issues/22
- [ ] https://github.com/Quansight-Labs/czi-scientific-python-mgmt/issues/24
- [ ] https://github.com/Quansight-Labs/czi-scientific-python-mgmt/issues/27
- [ ] https://github.com/Quansight-Labs/czi-scientific-python-mgmt/issues/31
```

## 🔗  Additional links

- Currently tracked in https://github.com/pydata/pydata-sphinx-theme/issues/1079
- [Accessible current page navigation](https://www.callumhart.com/blog/an-accessible-current-page-navigation-state/)
- [Tips for focus styles](https://www.nicchan.me/blog/tips-for-focus-styles/)
- [Focusing on focus styles](https://css-tricks.com/focusing-on-focus-styles/)
- [Accessible icons links](https://kittygiraudel.com/2020/12/10/accessible-icon-links/)
- [Inclusive components](https://inclusive-components.design/)
- [Unambiguous click menu](https://css-tricks.com/in-praise-of-the-unambiguous-click-menu/)
- [CSS and JS a11y best practices](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/CSS_and_JavaScript)
- [A guide to accessible focus indicators](https://www.sarasoueidan.com/blog/focus-indicators/)
