### ISSUE TITLE
TEST - Add automated accessibility tests to the PyData Sphinx theme

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-scientific-python-mgmt#23]
## 📝 Summary

As we work on improving WCAG conformance and accessibility remediation, we must also ensure we can detect regressions and run automated audits (as possible) of the theme. 

```[tasklist]
### Tasks
- [ ] https://github.com/pydata/pydata-sphinx-theme/issues/1168
- [ ] https://github.com/Quansight-Labs/czi-scientific-python-mgmt/issues/28
- [ ] https://github.com/pydata/pydata-sphinx-theme/issues/1378
```

## Additional details

- Definition of done: 
	- a minimal set of tests with Playwright and axe-core run on the Kitchen sink theme (for both dark and light theme)
	- documentation in the accessibility section of the developer docs
- Follow-up:
	- As this is a testing MVP we would need to iterate on reporting and expanding the tests based on the theme and needs
