### ISSUE TITLE
PyData Sphinx - keyboard navigation

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-scientific-python-mgmt#25]
Tracking progress towards keyboard navigation improvements in the PyData Sphinx theme. 

The goal is to make the theme fully operable with a keyboard only.

```[tasklist]
### Initial work
- [x] Keyboard navigation event
- [x] Open issues on the PyData Sphinx repo
- [x] Address any keyboard issues identified in https://github.com/pydata/pydata-sphinx-theme/issues/1403
```

There are still some areas that need auditing/testing, so there are additional tasks to carry on:

```[tasklist]
### Tasks
- [x] Perform a second keyboard navigation event
- [x] Add documentation on docs-site keyboard navigation events in accessibility handbook
```

**Comment by trallard** [comment]
This happened - Tania needs to follow up on the actions and opening issues on the pydata sphinx repo
