### ISSUE TITLE
ENH - Improve reporting of automated tests

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-scientific-python-mgmt#28]
The goal of this task is to improve the reporting of the accessibility tests beyond logs

```[tasklist]
### Tasks
- [x] Get the full json artefacts for the tests
- [x] Add reporting functionality for each page
- [ ] Publish the reports within the GH action workflows
```
