### ISSUE TITLE
Set up handbook infrastructure

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-scientific-python-mgmt#29]
```[tasklist]
### Tasks
- [x] Create a repo under Quansight Labs org (BSD-3)
- [x] Set up documentation engine (Docusaurus?)
- [ ] Add pre-commit hooks and other linters needed
- [ ] Add netlify for serving and previews
```

**Comment by trallard** [comment]
Initial repo lives at https://github.com/Quansight-Labs/a11y-playbook
