### ISSUE TITLE
Develop handbook content outline and scope

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-scientific-python-mgmt#30]
Three main personas we have discussed in the past for the handbook scope are:

- Maintainers (of open source projects)
- Contributors to open-source projects
- Content creators (think docs, notebooks, papers, viz)

Based on those personas, we need to define the relevant content required. 

```[tasklist]
### Content creators
- [ ] Notebook authoring guide (see https://github.com/Quansight-Labs/jupyter-a11y-mgmt/issues/173 and https://github.com/jupyter/accessibility/issues/125)
- [ ] Alt-text guide
```

```[tasklist]
### Maintainers
- [ ] Conducting user research with disabled users
- [ ] Reviewing PRs for a11y https://github.com/jupyter/accessibility/issues/125#issuecomment-1511706493
- [ ] Accessibility docs best practices https://github.com/jupyter/accessibility/issues/15
- [ ] How to - evaluate keyboard navigation
- [ ] Quick accessibility audit and reporting for documentation sites
```

## Resources 📖

- [Writing documentation with neurodivergent oss contributors in mind](https://www.slideshare.net/CKRinOliver/writing-documentation-with-neurodivergent-oss-contributors-in-mind-1)
- [Let me learn](https://tatianamac.com/posts/let-me-learn/)
- [Write the Docs accessibility guide](https://www.writethedocs.org/guide/writing/accessibility/)
- [Best Practices for Image Text Alternatives](https://knowbility.org/blog/2021/best-practices-for-image-text-alternatives)
- [An Alt Decision Tree](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [Accessibility Concerns for Content Staff](https://blog.tenon.io/accessibility-concerns-for-content-staff/)
- [Creating accessible documentation](https://letters4sneha.medium.com/the-tech-writers-journal-7-creating-accessible-documentation-eb2c011ac83c)
- [Open docs guide](https://github.com/google/opendocs/tree/main/audit?rgh-link-date=2021-02-05T17%3A58%3A43Z)
