### ISSUE TITLE
SCOPING - Evaluate if we need to account for ATAG guidelines

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-scientific-python-mgmt#38]
In addition to WCAG, there is also the [ATAG (Authoring Tool accessibility guidelines)](https://www.w3.org/WAI/standards-guidelines/atag/).

These guidelines apply to documentation engines as per their [definition of authoring tools](http://www.w3.org/TR/ATAG20/#def-Authoring-Tool)

> software for generating websites, for example, content management systems (CMS) and learning management systems (LMS), courseware tools, content aggregators, no-code website builders
software that converts documents to web content technologies, for example, word processors and other office document applications with Save as HTML or EPUB

```[tasklist]
### Tasks
- [ ] Asses which guidelines apply to documentation engines
- [ ] Identify and document success criteria
- [ ] Scope a plan for implementation (evaluation, remediation, documentation)
``` 

## Resources 📖 

- [Implementing ATAG](https://www.w3.org/TR/IMPLEMENTING-ATAG20/)
- [ATAG Report tool](https://www.w3.org/WAI/atag/report-tool/) -> akin to the accessibility statement but focuses on ATAG affordances (did not know this existed 👀)
