### ISSUE TITLE
a11y weekly sync - 22/08/2023

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-scientific-python-mgmt#39]
Opening this issue to track our weekly progress and discussions

cc/ @gabalafou @smeragoel 
```[tasklist]
### Tasks
- [ ] @gabalafou - type issues for button https://docs.google.com/document/d/1BLhk39l2KfftYLAf_vs5WZjREKWQGBOz-t7Iwyd0Cnc/edit
- [ ] Fix button on Sphinx Design - will need to open an issue first @gabalafou
- [ ] We will wait until Smera is back from PTO to discuss focus (button) again
```

**Comment by trallard** [comment]
- Discussed https://github.com/pydata/pydata-sphinx-theme/pull/1414
	- Decision: turn off transitions
