### ISSUE TITLE
Accessibility audit PST (PyData Sphinx Theme)

### ISSUE THREAD

**Issue by gabalafou** [Quansight-Labs/czi-scientific-python-mgmt#41]
## 📝 Summary

This issue is to track work and progress towards an accessibility audit of the [PyData Sphinx Theme](https://pydata-sphinx-theme.readthedocs.io/en/latest/index.html).

## 🚀 Tasks / Deliverables

- [x] [Brainstorm](https://docs.google.com/document/d/1I1zuaRNLf_2RVq5C4nr3GXsOMYI_nYGeGr99ndB56m0/edit)
- [x] Agree on approach: perform audit together as a group across several virtual sessions
- [x] Agree on tools: Accessibility Insights wizard?
- [x] Produce audit report
- [x] Create GitHub issues from report
- [x] create an accessibility statement
- [ ] document our auditing process in the Accessibility handbook

## 📅 Estimated completion

Finish audit sessions: early to mid November
Produce audit report:  late November
Create GitHub issues from report by end of year

## 📋 Additional information

- As part of the audit, we should check how PST looks in reader modes across various browsers and apps.
- Look at DOM structure and accessibility tree
- What about [search landmark](https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/search.html)?
