### ISSUE TITLE
List of focus ring aberrations

### ISSUE THREAD

**Issue by gabalafou** [Quansight-Labs/czi-scientific-python-mgmt#49]
## Summary

While working on https://github.com/pydata/pydata-sphinx-theme/pull/1549, I created a list of focus ring TODOs. I'm creating this issue to make sure that they are tracked somewhere.

## Tasks to complete

- [x] Sphinx Design link cards (as seen on the home page) - focus ring is broken (squished, very narrow) due to the way the link is rendered
- [x] Sidebar TOC dropdown "chevron" button (does not receive focus and does not work with space or enter key)
- [x] Focus ring for [tabs](http://[::]:8000/user_guide/web-components.html#tabs) not yet implemented
- [x] Toggle (hamburger) button for left/primary mobile sidebar overlay (does not receive focus and does not work with space key or enter key). Open question: does it need to work with keyboard? 
- [x] [Button](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/web-components.html#badges-and-button-links) focus rings need to be changed to match the color of the button
- [x] Toggle (hamburger) button for right/secondary mobile sidebar overlay (receives focus, has focus ring, but does not respond to space or enter key). Open question: does it need to work with keyboard? 
  - https://github.com/pydata/pydata-sphinx-theme/pull/1585
- [x] Some weird artifact for API "source" links, where a second blank focus ring appears at the end of the API method name:
  <img width="698" alt="screenshot showing the two focus rings" src="https://github.com/pydata/pydata-sphinx-theme/assets/317883/fe3722f1-97d2-46ed-a7ce-16055c71604b">
  - https://github.com/pydata/pydata-sphinx-theme/pull/1778
- [ ] There are too many copy buttons in [notebook outputs](https://pydata-sphinx-theme.readthedocs.io/en/latest/examples/pydata.html)
- [ ] [ipyleaflet](https://pydata-sphinx-theme.readthedocs.io/en/latest/examples/pydata.html#ipyleaflet) receives focus but does not show focus ring

**Comment by gabalafou** [comment]
https://github.com/pydata/pydata-sphinx-theme/pull/1778
