### ISSUE TITLE
[META] PyData Sphinx Theme Accessibility Audit Issue Tracker

### ISSUE THREAD

**Issue by smeragoel** [Quansight-Labs/czi-scientific-python-mgmt#54]
## 📝 Summary
This is a meta issue created to track the remediation tasks for accessibility improvements based on the areas identified from our recent accessibility audit.

```[tasklist]
## 📌 Tasks
- [ ] #55
- [ ] #56
- [ ] Focus
- [ ] https://github.com/Quansight-Labs/czi-scientific-python-mgmt/issues/63
- [ ] https://github.com/Quansight-Labs/czi-scientific-python-mgmt/issues/61
- [ ] https://github.com/Quansight-Labs/czi-scientific-python-mgmt/issues/57
- [ ] https://github.com/Quansight-Labs/czi-scientific-python-mgmt/issues/58
- [ ] https://github.com/Quansight-Labs/czi-scientific-python-mgmt/issues/64
- [ ] https://github.com/Quansight-Labs/czi-scientific-python-mgmt/issues/59
- [ ] https://github.com/Quansight-Labs/czi-scientific-python-mgmt/issues/60
```
## ℹ Additional Information
- The audit was conducted using [Accessibility Insights](https://accessibilityinsights.io/) on the target page [The PyData Sphinx Theme — PyData Theme 0.15.2 documentation](https://pydata-sphinx-theme.readthedocs.io/en/stable/)
- Initial findings are based on the homepage, but solutions may improve site-wide accessibility.

## 📑 Assessment Report
[Assessment_20240131_ThePyDataSphinxTheme.json](https://github.com/Quansight-Labs/czi-scientific-python-mgmt/files/14190700/Assessment_20240131_ThePyDataSphinxTheme.json)

This is an automatically generated report that shows the overall accessibility of the website through a combination of automated and manual tests that cover all the WCAG 2.1 AA success criteria.
