### ISSUE TITLE
May 2024 PyData Theme audit findings

### ISSUE THREAD

**Issue by gabalafou** [Quansight-Labs/czi-scientific-python-mgmt#72]
```[tasklist]
### Tasks

- [ ] There are two separate hierarchies of headings on the page (section navigation and the main article)
   - Should the "on this page" navigation have headings?
      - Argument against: the area can be reached via landmarks
      - Argument for: the section navigation has heading so it feels like a inconsistency in UX
- [ ] The light/dark toggle button does not communicate its state
- [ ] Sphinx-togglebutton expand/collapse button does not communicate its state
- [ ] Sphinx-copybutton is not visible until hovered or focused
- [ ] Tabs need other hover indicator other than just color change (underlining?)
- [ ] Dropdown admonition chevrons hover effect is a little too subtle?
- [ ] Copy button tool tip (native/browser does not meet criteria, does the other one meet the criteria, do we need both?)
- [ ] Not enough space between navbar icon buttons
- [ ] Not enough space between the links in the "on this page" navigation
- [ ] Search input modal allows user to tab away from it without explicitly dismissing it
- [ ] Mobile sidebar modal allows user to tab away from it without explicitly dismissing it
- [ ] Search input modal does not return focus to opener (search button) when modal is closed
- [ ] Read the Docs version switcher is not reachable using only keyboard (tab key)
- [ ] Read the Docs switcher is sometimes on the left below the section navigation, sometimes fixed to the lower right portion of the viewport.
   - From Accessibility Insights audit: Functional components that appear on multiple pages must be identified consistently. 
- [ ] Are there any divergent links? Find and fix all divergent links (same name, different URLs)
- [ ] Are there any convergent links? Review on case-by-case basis
- [ ] Some components do not respond to user text spacing adjustment: 
   - Version switcher trigger button
   - Search bar trigger button
   - Search bar input
   - More dropdown trigger button
- [ ] Tooltips for the icon links/buttons in nav bar are neither dismissible nor hoverable
- [ ] Needs investigation: does search button (magnifying glass) on mobile meet [WCAG 1.4.11](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html)? More generally, is it putting our best foot forward?
- [ ] Assistive tech does not have access to the "external link" icon next to external links in the nav bar (such as the "Changelog" link in the PyData Theme docs)
- [ ] All the icon links in the nav bar are just a tiny bit too narrow (less than 24 css pixels)
- [ ] The hover+focus state of the nav bar icon links do not look good
- [ ] The anchor links (next to the headings and only visible on hover) do not have sufficient contrast with the site background
Content that appears on focus or hover must be dismissible, hoverable, and persistent.

**Comment by gabalafou** [comment]
Derived from #70 and [our shared Google Drive folder where the Accessibility Insights audits were saved](https://drive.google.com/drive/u/0/folders/1hlNi0426vwzZUbJUPhMWATIo5-v2VIDY)

**Comment by gabalafou** [comment]
Notes from today's sync (May 23)

Question - other audit checks beyond accessibility insights?

- Turn off CSS, what happens?
- Turn off JavaScript, what happens?

Tania suggests:

- a screen reader audit through Fable. Clarify: after we address our own audit.
- check against [ATAG](https://www.w3.org/WAI/standards-guidelines/atag/)

**Comment by trallard** [comment]
`copybutton` identified issues:
- there is not enough contrast on hover (light mode, dark mode needs checks)
- there are two tooltips displayed at all times -> need to remove one
- whichever we use need to be visible in high contrast mode
- needs check: ARIA should be applied accordingly in which case the SVG is purely decorative (icon)

**Comment by Carreau** [comment]
> Derived from #70 and [our shared Google Drive folder where the Accessibility Insights audits were saved](https://drive.google.com/drive/u/0/folders/1hlNi0426vwzZUbJUPhMWATIo5-v2VIDY)

Can/should this be made public ?

**Comment by Carreau** [comment]
[Accessibility insight](https://accessibilityinsights.io/docs/web/overview/) is a browser extension. I'll try to move some of the relevant files to this repository and try to add some details on how to use it.
