### ISSUE TITLE
WCAG compliance - Scientific Computing Hugo theme

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-scientific-python-mgmt#9]
## 📝 Summary

The current status of the Scientific Computing Hugo theme WCAG compliance is unknown (at this time).
Through this deliverable we will work towards meeting compliance for WCAG 2.1 AA and aim for the theme to be accessible by:

- Screen reader users
- low vision users

## 🚀 Tasks / Deliverables

- [ ] Perform an accessibility audit of the Scientific Computing Hugo theme
- [ ] Accessibility remediation work - design and UX/UI
- [ ] Accessibility remediation work - web development
- [ ] Develop and publish a WCAG compliance statement for the Scientific Computing Hugo theme
- [ ] Stretch: consider COGA recommendations

## 📅 Estimated completion

[12 months milestone](https://github.com/Quansight-Labs/czi-scientific-python-mgmt/milestone/1)

## 📋 Additional information

- [WCAG accessibility guidelines](https://www.w3.org/TR/WCAG21/)
- UK gov - [accessibility primer: code](https://alphagov.github.io/wcag-primer/design.html)
- UK gov - [accessibility primer: design](https://alphagov.github.io/wcag-primer/design.html)
- [How to meet WCAG - quick reference](https://www.w3.org/WAI/WCAG21/quickref/)
- gov.uk - [testing for accessibility](https://www.gov.uk/service-manual/helping-people-to-use-your-service/testing-for-accessibility)
- gov.uk - [doing a basic accessibility audit](https://www.gov.uk/government/publications/doing-a-basic-accessibility-check-if-you-cant-do-a-detailed-one/doing-a-basic-accessibility-check-if-you-cant-do-a-detailed-one)
- W3C COGA WG - [Making content usable for people with cognitive and learning disabilities](https://w3c.github.io/coga/content-usable/)
- W3C COGA WG - [gh repository](https://github.com/w3c/coga)

**Comment by trallard** [comment]
This work is currently blocked on the Hugo side of things while we wait for feedback and guidance on when the remediation work will happen
